export enum eventBusKey {
  LanguageEvent = 'LanguageEvent',
  WifiEvent = 'WifiEvent', // 连接WiFi事件，后台通讯用
  StopEvent = 'StopEvent',
  ElectricEvent = 'ElectricEvent',
  StatusEvent = 'StatusEvent',
  IdEvent = 'IdEvent',
  OrbitEvent = 'OrbitEvent',
  OrbitChangeEvent = 'OrbitChangeEvent',
  NodeEvent = 'NodeEvent',
  NodeChangeEvent = 'NodeChangeEvent',
  OverageEvent = 'OverageEvent',
  ChangeEvent = 'ChangeEvent',
  RebootEvent = 'RebootEvent',
  DownEvent = 'DownEvent',
  ErrorEvent = 'ErrorEvent',
  SendCmdEvent = 'SendCmdEvent',
  GunErrorEvent = 'gunError',
  MksEvent = 'MksEvent',
  BackBoardEvent = 'BackBoardEvent',
  FrontBoardEvent = 'FrontBoardEvent',
}
